### ISSUE TITLE
Trouble run on local development

### ISSUE THREAD

**Issue by singgihpr** [HugoRCD/canvas#68]
### Description

Hi Hugo and team,

I was just about to try out this beautiful template, 
but when I finished installing the dependencies and ran `bun dev` I got an error 
`[worker reload] [worker init] Package import specifier "#content/server" is not defined in package` 
which points to the sitemap.xml.ts file.

Is there something I'm missing?

Regards

**Comment by HugoRCD** [comment]
Thanks !!!! I just pushed a fix for some bugs I found, I don't know if it will solve the problem but try it just in case and if it still doesn't work I'll do more research !

**Comment by singgihpr** [comment]
Nice, it's work like charm!
